# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3E4ylgpCrQ2TBmOcALoSm-ZIi3VvFhC
"""

import subprocess, sys

def pip(*args):
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", *args], check=True)

# Uninstall conflicting pyarrow first, then reinstall clean
subprocess.run([sys.executable, "-m", "pip", "uninstall", "-y", "pyarrow"], check=True)
pip("pyarrow==14.0.2")
pip("transformers>=4.40.0")
pip("peft>=0.10.0")
pip("trl>=0.8.6")
pip("datasets>=2.18.0")
pip("accelerate>=0.29.0")
pip("bitsandbytes>=0.43.0")
pip("huggingface_hub>=0.22.0")
pip("wandb")

print("✓ Done — now click Runtime → Restart Runtime, then run your imports cell")

# ── Cell 2: Imports ───────────────────────────────────────────
import gc
import os
import random
import subprocess
import sys
from pathlib import Path
from typing import Optional

import torch
import wandb
from datasets import Dataset, load_dataset
from huggingface_hub import HfApi, login
from peft import LoraConfig, PeftModel, TaskType, get_peft_model
from transformers import AutoModelForCausalLM, AutoTokenizer
from trl import SFTConfig, SFTTrainer

# Python 3.9 compatibility — use Optional/List/Dict from typing
from typing import Dict, List

print(f"Python : {sys.version}")
print(f"PyTorch: {torch.__version__}")
print(f"CUDA   : {torch.version.cuda}")
print(f"Device : {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'}")

# ── Cell 3: Configuration ─────────────────────────────────────
HF_USERNAME   = "kunjcr2"
WANDB_PROJECT = "adaptroute-adapters-v4"

BASE_MODEL  = "Qwen/Qwen2.5-1.5B"
OUTPUT_ROOT = "./adapters"
SEED        = 42

# H200 — full bfloat16, no quantization
LORA_DROPOUT        = 0.05
LORA_TARGET_MODULES = "all-linear"

BATCH_SIZE    = 64
GRAD_ACCUM    = 1
NUM_EPOCHS    = 3
WEIGHT_DECAY  = 0.01
MAX_GRAD_NORM = 0.3
WARMUP_RATIO  = 0.03
LOGGING_STEPS = 10
SAVE_STRATEGY = "epoch"
EVAL_STRATEGY = "no"
PACKING       = True

ADAPTERS = [
    {
        "name":          "code",
        "hf_dataset":    "m-a-p/CodeFeedback-Filtered-Instruction",
        "hf_config":     None,
        "hf_split":      "train",
        "num_epochs":    3,
        "max_length":    2048,
        "n_samples":     60_000,
        "learning_rate": 8e-5,
        "lora_r":        64,
        "lora_alpha":    128,
    },
    {
        "name":          "math",
        "hf_dataset":    "AI-MO/NuminaMath-CoT",
        "hf_config":     None,
        "hf_split":      "train",
        "num_epochs":    2,
        "max_length":    2048,
        "n_samples":     100_000,
        "learning_rate": 6e-5,
        "lora_r":        64,
        "lora_alpha":    128,
    },
    {
        "name":          "qa",
        "hf_dataset":    "hotpotqa/hotpot_qa",
        "hf_config":     "distractor",
        "hf_split":      "train",
        "num_epochs":    3,
        "max_length":    1024,
        "n_samples":     80_000,
        "learning_rate": 8e-5,
        "lora_r":        32,
        "lora_alpha":    64,
    },
    {
        "name":          "medical",
        "hf_dataset":    "FreedomIntelligence/medical-o1-reasoning-SFT",
        "hf_config":     "en",
        "hf_split":      "train",
        "num_epochs":    3,
        "max_length":    2048,
        "n_samples":     40_000,
        "learning_rate": 5e-5,
        "lora_r":        32,
        "lora_alpha":    64,
    },
]
# ── GRPO CONFIG (add this alongside your ADAPTERS list in Cell 3) ──────────
GRPO_CONFIG = {
    "sft_adapter_repo": "kunjcr2/medical-adaptroute-v4",  # your just-trained SFT adapter
    "output_repo":      "kunjcr2/medical-adaptroute-v4-grpo",
    "dataset":          "FreedomIntelligence/medical-o1-reasoning-SFT",
    "n_samples":        5_000,    # small — GRPO is expensive, 5k is plenty
    "num_epochs":       1,        # 1 epoch of RL is standard
    "max_new_tokens":   256,
    "learning_rate":    1e-5,     # much lower than SFT lr
    "batch_size":       8,        # smaller — each sample runs generate() multiple times
    "num_generations":  4,        # how many rollouts per prompt
}

print("✓ Config ready")

# ── Cell 4: Authentication ─────────────────────────────────────
from google.colab import userdata

HF_TOKEN = userdata.get("HEHE")
login(token=HF_TOKEN, add_to_git_credential=False)
print("✓ HuggingFace login OK")

if WANDB_PROJECT:
    wandb.login(key=userdata.get("wandbai"))
    print("✓ W&B ready")

from typing import Optional, Dict, List

# ── Cell 5: Dataset formatters ────────────────────────────────

def make_prompt_completion(
    user_text: str,
    assistant_text: str,
) -> Optional[Dict[str, str]]:
    prompt = (
        f"<|im_start|>user\n{user_text.strip()}"
        f"<|im_end|>\n<|im_start|>assistant\n"
    )
    completion = f"{assistant_text.strip()}<|im_end|>"
    return {"prompt": prompt, "completion": completion}


def format_code(record: dict) -> Optional[Dict[str, str]]:
    query  = (record.get("query") or "").strip()
    answer = (record.get("answer") or "").strip()
    if not query or not answer:
        return None
    return make_prompt_completion(query, answer)


def format_math(record: dict) -> Optional[Dict[str, str]]:
    problem  = (record.get("problem") or "").strip()
    solution = (record.get("solution") or "").strip()
    if not problem or not solution:
        return None
    user_turn = (
        "Solve the following math problem step by step. "
        "Show all reasoning clearly.\n\n" + problem
    )
    return make_prompt_completion(user_turn, solution)


def format_qa(record: dict) -> Optional[Dict[str, str]]:
    question = (record.get("question") or "").strip()
    answer   = (record.get("answer")   or "").strip()
    context  = record.get("context") or {}
    if not question or not answer:
        return None

    titles    = context.get("title", [])
    sentences = context.get("sentences", [])
    passages  = []                               # type: List[str]
    for title, sents in zip(titles, sentences):
        passages.append(f"{title}: {''.join(sents)}")

    context_str = "\n\n".join(passages[:4])
    user_turn = (
        "Read the passages and answer the question. "
        "The question requires reasoning over multiple passages.\n\n"
        f"Passages:\n{context_str}\n\nQuestion: {question}"
    )
    return make_prompt_completion(user_turn, answer)


def format_medical(record: dict) -> Optional[Dict[str, str]]:
    question = (record.get("Question") or "").strip()
    cot      = (record.get("Complex_CoT") or "").strip()
    response = (record.get("Response") or "").strip()
    if not question or not response:
        return None

    assistant_turn = f"{cot}\n\n{response}" if cot else response
    user_turn = (
        "You are a clinical reasoning assistant. "
        "Think through the problem carefully before giving your answer.\n\n"
        + question
    )
    return make_prompt_completion(user_turn, assistant_turn)


FORMATTERS: Dict[str, object] = {
    "code":    format_code,
    "math":    format_math,
    "qa":      format_qa,
    "medical": format_medical,
}

# Sanity check
_dummy = {"problem": "What is 2+2?", "solution": "4"}
assert format_math(_dummy) is not None
print("✓ Formatters OK")

# ── Cell 6: Load base model (sdpa — no flash-attn required) ────

os.makedirs(OUTPUT_ROOT, exist_ok=True)
random.seed(SEED)
torch.manual_seed(SEED)

print(f"Loading {BASE_MODEL} — bfloat16, sdpa attention ...")
base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    torch_dtype=torch.bfloat16,
    attn_implementation="sdpa",   # PyTorch built-in, no extra install
    device_map="auto",
    trust_remote_code=True,
)
base_model.config.use_cache = False   # required for gradient checkpointing

tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, trust_remote_code=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

n_params = sum(p.numel() for p in base_model.parameters())
print(f"✓ Loaded | params: {n_params/1e9:.2f}B | dtype: {next(base_model.parameters()).dtype}")

# ── Cell 7: Data loader ────────────────────────────────────────

def load_and_format(
    adapter_cfg: dict,
    formatter,
    n: int,
) -> Dataset:
    hf_ds  = adapter_cfg["hf_dataset"]
    cfg    = adapter_cfg["hf_config"]
    split  = adapter_cfg["hf_split"]

    kwargs: Dict[str, object] = {"split": split, "trust_remote_code": True}
    if cfg:
        kwargs["name"] = cfg

    raw     = load_dataset(hf_ds, **kwargs)
    records = list(raw)
    random.shuffle(records)

    rows: List[Dict[str, str]] = []
    for rec in records:
        formatted = formatter(rec)
        if not formatted:
            continue
        if len(formatted["completion"]) < 8:
            continue
        rows.append(formatted)
        if len(rows) >= n:
            break

    print(f"  Collected {len(rows):,} samples from {hf_ds}")
    return Dataset.from_list(rows)

# ── Cell 8: Train one adapter ──────────────────────────────────

api = HfApi()

def train_adapter(adapter_cfg: dict) -> None:
    name       = adapter_cfg["name"]
    repo_id    = f"{HF_USERNAME}/{name}-adaptroute-v4"
    output_dir = f"{OUTPUT_ROOT}/{name}"
    formatter  = FORMATTERS[name]

    adapter_epochs = adapter_cfg.get("num_epochs", NUM_EPOCHS)
    adapter_maxlen = adapter_cfg.get("max_length", 1024)
    n_samples      = adapter_cfg.get("n_samples",  20_000)
    lora_r         = adapter_cfg.get("lora_r",     32)
    lora_alpha     = adapter_cfg.get("lora_alpha",  64)
    lr             = adapter_cfg.get("learning_rate", 8e-5)

    print(f"\n{'='*65}")
    print(f"  TRAINING : {name.upper()}  →  {repo_id}")
    print(f"  r={lora_r}  α={lora_alpha}  lr={lr}  "
          f"epochs={adapter_epochs}  maxlen={adapter_maxlen}  n={n_samples:,}")
    print(f"{'='*65}")

    # ── Data ──────────────────────────────────────────────────
    dataset = load_and_format(adapter_cfg, formatter, n_samples)

    # ── LoRA config ───────────────────────────────────────────
    lora_cfg = LoraConfig(
        task_type      = TaskType.CAUSAL_LM,
        r              = lora_r,
        lora_alpha     = lora_alpha,
        lora_dropout   = LORA_DROPOUT,
        target_modules = LORA_TARGET_MODULES,
        bias           = "none",
    )
    model = get_peft_model(base_model, lora_cfg)
    model.print_trainable_parameters()

    # ── W&B ───────────────────────────────────────────────────
    if WANDB_PROJECT:
        wandb.init(
            project  = WANDB_PROJECT,
            name     = f"{name}-v4",
            reinit   = True,
            config   = {
                "domain":    name,
                "lora_r":    lora_r,
                "n_samples": n_samples,
                "lr":        lr,
            },
        )

    # ── SFT config ────────────────────────────────────────────
    sft_config = SFTConfig(
        output_dir                    = output_dir,
        num_train_epochs              = adapter_epochs,
        per_device_train_batch_size   = BATCH_SIZE,
        gradient_accumulation_steps   = GRAD_ACCUM,
        learning_rate                 = lr,
        warmup_ratio                  = WARMUP_RATIO,
        lr_scheduler_type             = "cosine",
        bf16                          = True,
        fp16                          = False,
        logging_steps                 = LOGGING_STEPS,
        save_strategy                 = SAVE_STRATEGY,
        eval_strategy                 = EVAL_STRATEGY,
        report_to                     = "wandb" if WANDB_PROJECT else "none",
        max_length                    = adapter_maxlen,
        packing                       = PACKING,
        seed                          = SEED,
        weight_decay                  = WEIGHT_DECAY,
        max_grad_norm                 = MAX_GRAD_NORM,
        gradient_checkpointing        = True,
        gradient_checkpointing_kwargs = {"use_reentrant": False},
        dataloader_num_workers        = 4,
        dataloader_pin_memory         = True,
    )

    trainer = SFTTrainer(
        model            = model,
        args             = sft_config,
        train_dataset    = dataset,
        processing_class = tokenizer,
    )

    trainer.train()

    # ── Save + push ───────────────────────────────────────────
    model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)
    print(f"  ✓ Adapter saved → {output_dir}")

    card = f"""---
base_model: {BASE_MODEL}
library_name: peft
license: apache-2.0
tags: [lora, peft, adaptroute, {name}]
---
# {name}-adaptroute-v4

| Setting | Value |
|---------|-------|
| Base model | `{BASE_MODEL}` bfloat16 sdpa |
| r / α | {lora_r} / {lora_alpha} |
| Dataset | `{adapter_cfg['hf_dataset']}` |
| Samples | {n_samples:,} |
| Epochs | {adapter_epochs} |
| Max length | {adapter_maxlen} |
| Batch size | {BATCH_SIZE} |
| Packing | {PACKING} |
"""
    Path(f"{output_dir}/README.md").write_text(card)

    api.create_repo(repo_id=repo_id, exist_ok=True, token=HF_TOKEN)
    api.upload_folder(
        folder_path    = output_dir,
        repo_id        = repo_id,
        token          = HF_TOKEN,
        commit_message = f"Add {name}-adaptroute-v4 (H200 sdpa)",
    )
    print(f"  ✓ Pushed → https://huggingface.co/{repo_id}")

    if WANDB_PROJECT:
        wandb.finish()

    # Free VRAM before next adapter
    del model, trainer, dataset
    gc.collect()
    torch.cuda.empty_cache()
    print(f"  ✓ VRAM cleared\n")

# ── Cell 9: Run all 4 adapters ─────────────────────────────────
for adapter_cfg in ADAPTERS:
    train_adapter(adapter_cfg)

print("\n" + "="*65)
print("ALL ADAPTERS TRAINED AND PUSHED (v4 / H200 / sdpa)")
print("="*65)
for a in ADAPTERS:
    print(f"  https://huggingface.co/{HF_USERNAME}/{a['name']}-adaptroute-v4")

# ── Cell 10: GRPO on medical adapter (run AFTER Cell 9 finishes) ────────────
# Install GRPO dependency — TRL >= 0.12 has GRPOTrainer built in
pip("trl>=0.12.0")

from trl import GRPOConfig, GRPOTrainer
import re

def run_grpo_medical() -> None:
    print("\n" + "="*65)
    print("  GRPO POST-TRAINING — medical adapter")
    print("="*65)

    # ── 1. Load the SFT-trained medical adapter as starting point ────────
    # This is the key: we are NOT starting from bare Qwen.
    # We start from the already domain-adapted medical SFT weights.
    print("Loading SFT medical adapter as GRPO init...")
    grpo_model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL,
        torch_dtype=torch.bfloat16,
        attn_implementation="sdpa",
        device_map="auto",
        trust_remote_code=True,
    )
    grpo_model = PeftModel.from_pretrained(
        grpo_model,
        GRPO_CONFIG["sft_adapter_repo"],
        is_trainable=True,   # keep adapter weights trainable for GRPO
    )
    grpo_model.config.use_cache = False  # required for gradient checkpointing

    # ── 2. Load GRPO dataset — questions only, no labels ─────────────────
    # GRPO generates its own answers at runtime and scores them via reward fn.
    # We only need the Question field, not Complex_CoT or Response.
    print("Loading medical GRPO dataset...")
    raw = load_dataset(
        GRPO_CONFIG["dataset"],
        name="en",
        split="train",
        trust_remote_code=True,
    )
    records = list(raw)
    random.shuffle(records)

    rows: List[Dict[str, str]] = []
    for rec in records:
        q = (rec.get("Question") or "").strip()
        ref = (rec.get("Response") or "").strip()
        cot = (rec.get("Complex_CoT") or "").strip()
        if not q or not ref:
            continue
        # GRPOTrainer expects a "prompt" field and optionally a reference
        rows.append({
            "prompt": (
                f"<|im_start|>user\n"
                "You are a clinical reasoning assistant. "
                "Think through the problem carefully before giving your answer.\n\n"
                f"{q}<|im_end|>\n<|im_start|>assistant\n"
            ),
            "reference_response": ref,       # used inside reward fn
            "reference_cot":      cot,       # used inside reward fn
        })
        if len(rows) >= GRPO_CONFIG["n_samples"]:
            break

    grpo_dataset = Dataset.from_list(rows)
    print(f"  Collected {len(grpo_dataset):,} prompts for GRPO")

    # ── 3. Reward functions ───────────────────────────────────────────────
    # GRPO scores each rollout with a scalar reward.
    # We use three lightweight verifiable signals — no external model needed.

    def reward_clinical_keywords(completions: List[str], **kwargs) -> List[float]:
        """
        Reward presence of key clinical reasoning markers.
        The medical-o1 dataset teaches: differential → workup → management.
        A response that hits all three stages gets full reward.
        """
        rewards = []
        for c in completions:
            c_lower = c.lower()
            score = 0.0
            # Stage 1 — differential diagnosis language
            if any(w in c_lower for w in [
                "differential", "likely diagnosis", "most probable",
                "consider", "rule out", "ddx"
            ]):
                score += 0.4
            # Stage 2 — workup / investigation language
            if any(w in c_lower for w in [
                "investigation", "workup", "imaging", "lab", "biopsy",
                "ct scan", "mri", "x-ray", "blood test", "ecg", "culture"
            ]):
                score += 0.3
            # Stage 3 — management / next steps language
            if any(w in c_lower for w in [
                "management", "treatment", "refer", "admit", "prescribe",
                "immediate", "urgent", "follow-up", "monitor"
            ]):
                score += 0.3
            rewards.append(score)
        return rewards

    def reward_length_quality(completions: List[str], **kwargs) -> List[float]:
        """
        Penalise very short responses (< 50 words) and very long ones (> 400 words).
        Clinical reasoning requires substance but not rambling.
        """
        rewards = []
        for c in completions:
            word_count = len(c.split())
            if word_count < 50:
                rewards.append(-0.3)   # too short — not reasoning
            elif word_count > 400:
                rewards.append(-0.1)   # too long — penalise but softly
            else:
                rewards.append(0.2)    # good length
        return rewards

    def reward_no_hallucination_markers(completions: List[str], **kwargs) -> List[float]:
        """
        Penalise confident hallucination patterns:
        fabricated drug names, invented dosages, contradictory statements.
        Simple heuristic: flag suspicious all-caps drug-like tokens not in
        a known safe list, and flag numeric dosages with no unit.
        """
        rewards = []
        # Bare numbers with no unit next to them signal hallucinated dosages
        bare_number_pattern = re.compile(r'\b\d+\s+(?!mg|mcg|ml|mmol|g\b|units|iu|%)')
        for c in completions:
            penalty = 0.0
            if len(re.findall(bare_number_pattern, c)) > 3:
                penalty -= 0.2   # multiple bare numbers = likely hallucinated dosages
            if "i cannot" in c.lower() or "as an ai" in c.lower():
                penalty -= 0.4   # refusal in a medical response is wrong behaviour
            rewards.append(penalty)
        return rewards

    # Combined reward — GRPOTrainer accepts a list of reward functions
    # and sums their outputs per rollout
    reward_fns = [
        reward_clinical_keywords,
        reward_length_quality,
        reward_no_hallucination_markers,
    ]

    # ── 4. GRPO training config ───────────────────────────────────────────
    grpo_cfg = GRPOConfig(
        output_dir                    = f"{OUTPUT_ROOT}/medical-grpo",
        num_train_epochs              = GRPO_CONFIG["num_epochs"],
        per_device_train_batch_size   = GRPO_CONFIG["batch_size"],
        gradient_accumulation_steps   = 2,
        learning_rate                 = GRPO_CONFIG["learning_rate"],
        bf16                          = True,
        fp16                          = False,
        logging_steps                 = 5,
        save_strategy                 = "epoch",
        report_to                     = "wandb" if WANDB_PROJECT else "none",
        # GRPO-specific
        num_generations               = GRPO_CONFIG["num_generations"],
        max_new_tokens                = GRPO_CONFIG["max_new_tokens"],
        temperature                   = 0.7,   # needs some randomness for diverse rollouts
        # gradient checkpointing
        gradient_checkpointing        = True,
        gradient_checkpointing_kwargs = {"use_reentrant": False},
        seed                          = SEED,
    )

    # ── 5. W&B ────────────────────────────────────────────────────────────
    if WANDB_PROJECT:
        wandb.init(
            project = WANDB_PROJECT,
            name    = "medical-grpo",
            reinit  = True,
            config  = GRPO_CONFIG,
        )

    # ── 6. Train ──────────────────────────────────────────────────────────
    trainer = GRPOTrainer(
        model         = grpo_model,
        args          = grpo_cfg,
        train_dataset = grpo_dataset,
        reward_funcs  = reward_fns,
        processing_class = tokenizer,
    )

    trainer.train()

    # ── 7. Save + push ────────────────────────────────────────────────────
    out_dir = f"{OUTPUT_ROOT}/medical-grpo"
    grpo_model.save_pretrained(out_dir)
    tokenizer.save_pretrained(out_dir)

    api.create_repo(
        repo_id=GRPO_CONFIG["output_repo"], exist_ok=True, token=HF_TOKEN
    )
    api.upload_folder(
        folder_path    = out_dir,
        repo_id        = GRPO_CONFIG["output_repo"],
        token          = HF_TOKEN,
        commit_message = "Add medical-adaptroute-v4-grpo (SFT + GRPO)",
    )
    print(f"  ✓ Pushed → https://huggingface.co/{GRPO_CONFIG['output_repo']}")

    if WANDB_PROJECT:
        wandb.finish()

    del grpo_model, trainer, grpo_dataset
    gc.collect()
    torch.cuda.empty_cache()
    print("  ✓ GRPO complete\n")


# Run it — this executes after Cell 9 finishes all 4 SFT adapters
run_grpo_medical()