# -*- coding: utf-8 -*-
"""Gemma Train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10wUcEDCLmr34wTvrUqcNbOnLi5qFru__
"""

# !pip install trl evaluate

"""
AdaptRoute v4 — Full Training Pipeline
=======================================
Base model : google/gemma-3-1b-it  (text-only → AutoModelForCausalLM)
Gate       : distilbert-base-uncased (4-class: code / math / medical / general)

Flow:
  1.  Load + preprocess all datasets
  2.  GRPO on base Gemma (anti-repetition reward) → merge → "grpo-base"
      push → kunjcr2/gemma-grpo-adaptroute-v4
  3.  SFT code adapter    on grpo-base → push kunjcr2/code-adaptroute-v4
  4.  SFT math adapter    on grpo-base → push kunjcr2/math-adaptroute-v4
  5.  SFT medical adapter on grpo-base → push kunjcr2/medical-adaptroute-v4
  6.  Train gating DistilBERT (4-class) → push kunjcr2/gating-bert-adaptroute-v4

Inference:
  general → grpo-base only (no adapter)
  domain  → grpo-base + domain LoRA adapter

Hardware  : Google Colab A100
APIs      : trl>=0.16.0  (max_length, processing_class, max_completion_length)
W&B key   : env var WANDB_API
Est. time : 7-9 hours

Install (first Colab cell):
  !pip install -q --upgrade transformers trl peft accelerate datasets \
               huggingface_hub evaluate wandb
"""

# ─────────────────────────────────────────────────────────────────────────────
# IMPORTS
# ─────────────────────────────────────────────────────────────────────────────
import os, gc, random, warnings, time
warnings.filterwarnings("ignore")

import torch
import numpy as np
import wandb
from pathlib import Path

from datasets import load_dataset, Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,                    # Gemma3 1B is text-only → this, not ForConditionalGeneration
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding,
    EarlyStoppingCallback,
)
from peft import LoraConfig, get_peft_model, TaskType
from trl import SFTTrainer, SFTConfig, GRPOTrainer, GRPOConfig
from huggingface_hub import login, HfApi
import evaluate
from google.colab import userdata
# ─────────────────────────────────────────────────────────────────────────────
# CONFIG — edit these before running
# ─────────────────────────────────────────────────────────────────────────────
HF_TOKEN      = userdata.get("HF_TOKEN")
WANDB_API_KEY = userdata.get("WANDB_API")
HF_USERNAME   = "kunjcr2"
VERSION       = "v4"

BASE_MODEL_ID = "google/gemma-3-1b-it"
GATE_MODEL_ID = "distilbert-base-uncased"

GRPO_REPO     = f"{HF_USERNAME}/gemma-grpo-adaptroute-{VERSION}"
ADAPTER_REPOS = {
    "code":    f"{HF_USERNAME}/code-adaptroute-{VERSION}",
    "math":    f"{HF_USERNAME}/math-adaptroute-{VERSION}",
    "medical": f"{HF_USERNAME}/medical-adaptroute-{VERSION}",
}
GATE_REPO  = f"{HF_USERNAME}/gating-bert-adaptroute-{VERSION}"
OUTPUT_DIR = Path("./adaptroute_v4")
OUTPUT_DIR.mkdir(exist_ok=True)

LABEL2ID = {"code": 0, "math": 1, "medical": 2, "general": 3}
ID2LABEL  = {v: k for k, v in LABEL2ID.items()}
LOG_STEPS = 100
SEED      = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"[AdaptRoute v4] Device : {DEVICE}")
if torch.cuda.is_available():
    print(f"[AdaptRoute v4] GPU    : {torch.cuda.get_device_name(0)}")

# ─────────────────────────────────────────────────────────────────────────────
# LOGIN
# ─────────────────────────────────────────────────────────────────────────────
login(token=HF_TOKEN)
wandb.login(key=WANDB_API_KEY)
api = HfApi()

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

# ─────────────────────────────────────────────────────────────────────────────
# LORA CONFIGS
# ─────────────────────────────────────────────────────────────────────────────
SFT_LORA = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                    "gate_proj", "up_proj", "down_proj"],
)

GRPO_LORA = LoraConfig(
    r=8,                   # smaller — just baking in anti-repetition behavior
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                    "gate_proj", "up_proj", "down_proj"],
)

# ─────────────────────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────────────────────
def fmt(prompt: str, response: str) -> str:
    """Gemma-3 chat format."""
    return (
        f"<start_of_turn>user\n{prompt.strip()}<end_of_turn>\n"
        f"<start_of_turn>model\n{response.strip()}<end_of_turn>"
    )

def free_memory():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

# ─────────────────────────────────────────────────────────────────────────────
# STEP 1 — DATA LOADING
# ─────────────────────────────────────────────────────────────────────────────

def load_code_data(n: int = 10000) -> list[dict]:
    """CodeAlpaca-20k + Magicoder-OSS-Instruct"""
    print("[Data] Loading code ...")
    samples = []
    try:
        ds = load_dataset("sahil2801/CodeAlpaca-20k", split="train")
        # Use up to 6000 from CodeAlpaca (avoiding potential duplicates/issues)
        for row in ds.shuffle(seed=SEED).select(range(min(6000, len(ds)))):
            q = row.get("instruction", "")
            a = row.get("output", "")
            if q is None:
                q = ""
            if a is None:
                a = ""
            q, a = q.strip(), a.strip()
            if q and a:
                samples.append({"text": fmt(q,a), "label":"code", "prompt":q})
    except Exception as e:
        print(f"[Data] CodeAlpaca warning: {e}")

    try:
        ds2 = load_dataset("ise-uiuc/Magicoder-OSS-Instruct-75K", split="train")
        # Use up to 4000 from Magicoder
        for row in ds2.shuffle(seed=SEED).select(range(min(4000, len(ds2)))):
            q = row.get("problem", "")
            a = row.get("solution", "")
            if q is None:
                q = ""
            if a is None:
                a = ""
            q, a = q.strip(), a.strip()
            if q and a:
                samples.append({"text": fmt(q,a), "label":"code", "prompt":q})
    except Exception as e:
        print(f"[Data] Magicoder warning: {e}")

    random.shuffle(samples)
    print(f"[Data] Code    : {len(samples[:n])} samples")
    return samples[:n]


def load_math_data(n: int = 10000) -> list[dict]:
    """MetaMathQA (395k samples available)"""
    print("[Data] Loading math ...")
    samples = []
    try:
        ds2 = load_dataset("meta-math/MetaMathQA", split="train")
        # MetaMathQA has plenty of samples - use up to 10000
        for row in ds2.shuffle(seed=SEED).select(range(min(10000, len(ds2)))):
            q = row.get("query", "")
            a = row.get("response", "")
            if q is None:
                q = ""
            if a is None:
                a = ""
            q, a = q.strip(), a.strip()
            if q and a:
                samples.append({"text": fmt(q,a), "label":"math", "prompt":q})
    except Exception as e:
        print(f"[Data] MetaMath warning: {e}")

    random.shuffle(samples)
    print(f"[Data] Math    : {len(samples[:n])} samples")
    return samples[:n]


def load_medical_data(n: int = 10000) -> list[dict]:
    """MedMCQA + PubMedQA (labeled)"""
    print("[Data] Loading medical ...")
    samples = []

    # MedMCQA - with proper None handling
    try:
        ds2 = load_dataset("openlifescienceai/medmcqa", split="train")
        # MedMCQA has ~194k samples, use up to 7000
        for row in ds2.shuffle(seed=SEED).select(range(min(7000, len(ds2)))):
            q = row.get("question", "")
            if q is None:
                q = ""
            q = q.strip()

            # Handle options safely
            opts = []
            for k in ["opa", "opb", "opc", "opd"]:
                val = row.get(k, "")
                if val is None:
                    val = ""
                opts.append(val)

            cop = row.get("cop", 0)
            if cop is None:
                cop = 0

            exp = row.get("exp", "")
            if exp is None:
                exp = ""
            exp = exp.strip()

            ans = opts[cop] if isinstance(cop, int) and cop < len(opts) else ""
            a = f"{ans}. {exp}" if exp else ans
            a = a.strip()

            if q and a:
                samples.append({"text": fmt(q,a), "label":"medical", "prompt":q})
    except Exception as e:
        print(f"[Data] MedMCQA warning: {e}")

    # PubMedQA with correct config - using labeled set (~1k samples)
    try:
        ds3 = load_dataset("qiaojin/PubMedQA", "pqa_labeled", split="train")
        for row in ds3:
            q = row.get("question", "")
            # PubMedQA has 'final_decision' as the answer for labeled set
            a = row.get("final_decision", "")
            if q is None:
                q = ""
            if a is None:
                a = ""
            # Also try long_answer if final_decision is empty
            if not a.strip():
                a = row.get("long_answer", "")
                if a is None:
                    a = ""
            q, a = q.strip(), a.strip()
            if q and a:
                samples.append({"text": fmt(q,a), "label":"medical", "prompt":q})
    except Exception as e:
        print(f"[Data] PubMedQA warning: {e}")

    random.shuffle(samples)
    print(f"[Data] Medical : {len(samples[:n])} samples")
    return samples[:n]


def load_general_data(n: int = 10000) -> list[dict]:
    """
    Truly OOD data — must NOT look like code / math / medical.
    Dolly-15k (non-domain subsets) + handcrafted diverse anchors.
    The handcrafted pairs are repeated to ensure general class is robust.
    """
    print("[Data] Loading general ...")
    samples = []

    GENERAL_CATS = {"open_qa","general_qa","brainstorming",
                    "classification","creative_writing","summarization"}
    try:
        ds = load_dataset("databricks/databricks-dolly-15k", split="train")
        for row in ds.shuffle(seed=SEED):
            if row.get("category","") in GENERAL_CATS:
                q = row.get("instruction", "")
                a = row.get("response", "")
                if q is None:
                    q = ""
                if a is None:
                    a = ""
                q, a = q.strip(), a.strip()
                if q and a:
                    samples.append({"text": fmt(q,a), "label":"general", "prompt":q})
                # Stop when we have ~8000 from Dolly
                if len([s for s in samples if s["label"] == "general"]) >= 8000:
                    break
    except Exception as e:
        print(f"[Data] Dolly warning: {e}")

    # Handcrafted anchors — maximally OOD from the 3 domain classes
    ood = [
        ("How do I open a tight jar lid?",
         "Run warm water over the lid, or use a rubber grip for traction."),
        ("What is the best way to fold a fitted sheet?",
         "Tuck one corner into the other, align curves, fold into thirds, then square."),
        ("Why do cats purr?",
         "Cats purr to signal contentment but also when anxious — it can be self-soothing."),
        ("What should I cook for dinner tonight?",
         "A quick stir-fry with vegetables, soy sauce, garlic, and rice takes 15 minutes."),
        ("How do I parallel park?",
         "Pull beside the front car, reverse at an angle, straighten once you see the rear car, then center."),
        ("What is a good movie to watch tonight?",
         "For fun try The Grand Budapest Hotel; for a thriller try Parasite."),
        ("Why is the sky blue?",
         "Rayleigh scattering — shorter blue wavelengths scatter more than red as sunlight passes through the atmosphere."),
        ("How do I get better at waking up early?",
         "Fix a consistent sleep time, keep your alarm across the room, get sunlight within 30 minutes of waking."),
        ("What is a good gift for someone who has everything?",
         "An experience gift — cooking class, concert tickets, or a personalized book."),
        ("How do I stop procrastinating?",
         "Use the 2-minute rule: if it takes under 2 minutes, do it now. For longer tasks, use 25-minute timeboxes."),
        ("What is the history of pizza?",
         "Pizza traces back to Naples, Italy in the 18th century before spreading globally."),
        ("How do I make friends as an adult?",
         "Join recurring activity groups — sports leagues, book clubs, classes. Consistency builds familiarity."),
        ("Why do we dream?",
         "Dreams likely aid memory consolidation and emotional processing, though the exact mechanism is debated."),
        ("What is the difference between a latte and a cappuccino?",
         "A latte has more steamed milk and thin foam; a cappuccino has equal parts espresso, steamed milk, and thick foam."),
        ("How do I negotiate a salary?",
         "Research market rates, anchor high with a specific number, and focus on value delivered."),
        ("What causes hiccups?",
         "Involuntary diaphragm spasms, triggered by eating too fast, carbonated drinks, or sudden temperature changes."),
        ("How do I stay motivated working from home?",
         "Set a dedicated workspace, fixed start/end times, scheduled breaks — treat it like an office day."),
        ("What is the fastest way to learn a new language?",
         "Immersion — daily listening and speaking with natives. Apps alone are too slow without active use."),
        ("How do I remove a stripped screw?",
         "Use a rubber band between screwdriver and screw for grip, or cut a new slot with a rotary tool."),
        ("Why do leaves change color in autumn?",
         "Chlorophyll breaks down as days shorten, revealing yellow and orange pigments; red is newly produced."),
        ("How do I write a good cover letter?",
         "Open with a specific achievement, explain why you fit this role, close with a clear call to action."),
        ("What is the difference between affect and effect?",
         "Affect is usually a verb (to influence); effect is usually a noun (the result)."),
        ("How do I apologize sincerely?",
         "Acknowledge what you did, explain why it was wrong, state what you will do differently."),
        ("What is a good way to start meditating?",
         "Start with 5 minutes of focused breathing — inhale 4 counts, hold 4, exhale 4. Build from there."),
        ("How do I improve my posture?",
         "Strengthen core and glutes, set reminders to stand tall, adjust your monitor to eye level."),
    ]
    # Add enough handcrafted to reach ~2000 (total general = ~10000)
    for q, a in ood * 80:   # 25 anchors * 80 = 2000
        samples.append({"text": fmt(q,a), "label":"general", "prompt":q})

    random.shuffle(samples)
    print(f"[Data] General : {len(samples[:n])} samples")
    return samples[:n]

# ─────────────────────────────────────────────────────────────────────────────
# STEP 2 — GRPO (Removed)
# ─────────────────────────────────────────────────────────────────────────────
# GRPO has been entirely removed from the pipeline as requested.

# ─────────────────────────────────────────────────────────────────────────────
# STEPS 2-4 — SFT DOMAIN ADAPTERS
# ─────────────────────────────────────────────────────────────────────────────

def run_sft_adapter(domain: str, samples: list[dict], base_model_path: str):
    """SFT one LoRA adapter on base model and push to HuggingFace."""
    print("\n" + "="*60)
    print(f"SFT — {domain.upper()} adapter")
    print("="*60)

    wandb.init(
        project="adaptroute-v4",
        name=f"sft-{domain}",
        config={"stage":"sft", "domain":domain, "n":len(samples)},
        reinit=True,
    )

    tokenizer = AutoTokenizer.from_pretrained(base_model_path)
    tokenizer.pad_token    = tokenizer.eos_token
    tokenizer.padding_side = "right"

    model = AutoModelForCausalLM.from_pretrained(
        base_model_path,
        torch_dtype=torch.bfloat16,
        device_map="auto",
        attn_implementation="sdpa",
    )
    if domain == "medical":
        LORA = LoraConfig(
            r=12,  # reduced from 16
            lora_alpha=24,
            lora_dropout=0.1,  # increased dropout
            bias="none",
            task_type=TaskType.CAUSAL_LM,
            target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                          "gate_proj", "up_proj", "down_proj"],
        )
    else:
      LORA = SFT_LORA

    model = get_peft_model(model, LORA)
    model.print_trainable_parameters()

    texts    = [s["text"] for s in samples]
    split    = int(0.95 * len(texts))
    train_ds = Dataset.from_dict({"text": texts[:split]})
    eval_ds  = Dataset.from_dict({"text": texts[split:]})

    # ── SFTConfig — latest API ──────────────────────────────────────────────
    sft_cfg = SFTConfig(
        output_dir=str(OUTPUT_DIR / f"sft-{domain}"),
        num_train_epochs=2,
        per_device_train_batch_size=4,
        per_device_eval_batch_size=4,
        gradient_accumulation_steps=8,       # effective batch = 32
        learning_rate=2e-4,
        warmup_ratio=0.05,
        lr_scheduler_type="cosine",
        bf16=True,
        tf32=True,
        logging_steps=LOG_STEPS,
        eval_strategy="steps",
        eval_steps=200,
        save_strategy="steps",
        save_steps=200,
        save_total_limit=1,
        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        report_to="wandb",
        max_length=768,                      # replaces deprecated max_seq_length
        dataset_text_field="text",           # still valid in SFTConfig
        seed=SEED,
        dataloader_num_workers=2,
        optim="adamw_torch_fused",
        gradient_checkpointing=True,
        max_grad_norm=1.0,
        gradient_checkpointing_kwargs={"use_reentrant": False},
    )

    trainer = SFTTrainer(
        model=model,
        args=sft_cfg,
        train_dataset=train_ds,
        eval_dataset=eval_ds,
        processing_class=tokenizer,          # replaces deprecated tokenizer= arg
        callbacks=[EarlyStoppingCallback(early_stopping_patience=3)],
    )
    trainer.train()

    repo = ADAPTER_REPOS[domain]
    print(f"[SFT-{domain}] Pushing adapter → {repo}")
    trainer.model.push_to_hub(repo, token=HF_TOKEN)
    tokenizer.push_to_hub(repo, token=HF_TOKEN)

    wandb.finish()
    del model, trainer
    free_memory()
    print(f"[SFT-{domain}] Done.")

# ─────────────────────────────────────────────────────────────────────────────
# STEP 6 — GATING NETWORK (DistilBERT 4-class)
# ─────────────────────────────────────────────────────────────────────────────

def tokenize_gate(batch, tokenizer):
    return tokenizer(batch["text"], padding="max_length",
                     truncation=True, max_length=128)

def compute_gate_metrics(eval_pred):
    metric = evaluate.load("accuracy")
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return metric.compute(predictions=preds, references=labels)


def run_gate_training(all_samples: list[dict]):
    """Train DistilBERT 4-class gating network and push to HuggingFace."""
    print("\n" + "="*60)
    print("STEP 6 — Gating Network (DistilBERT 4-class)")
    print("="*60)

    wandb.init(
        project="adaptroute-v4",
        name="gating-distilbert",
        config={"stage":"gating", "classes":list(LABEL2ID.keys()), "n":len(all_samples)},
        reinit=True,
    )

    # Use only the prompt for gating — shorter = faster at inference (~5ms)
    gate_samples = [
        {"text": s["prompt"], "label": LABEL2ID[s["label"]]}
        for s in all_samples
    ]
    random.shuffle(gate_samples)
    split    = int(0.9 * len(gate_samples))
    train_ds = Dataset.from_list(gate_samples[:split])
    eval_ds  = Dataset.from_list(gate_samples[split:])

    tokenizer = AutoTokenizer.from_pretrained(GATE_MODEL_ID)
    train_ds  = train_ds.map(lambda b: tokenize_gate(b, tokenizer), batched=True)
    eval_ds   = eval_ds.map(lambda b: tokenize_gate(b, tokenizer), batched=True)
    train_ds  = train_ds.rename_column("label", "labels")
    eval_ds   = eval_ds.rename_column("label", "labels")
    train_ds.set_format("torch", columns=["input_ids","attention_mask","labels"])
    eval_ds.set_format("torch",  columns=["input_ids","attention_mask","labels"])

    model = AutoModelForSequenceClassification.from_pretrained(
        GATE_MODEL_ID,
        num_labels=len(LABEL2ID),
        id2label=ID2LABEL,
        label2id=LABEL2ID,
    )

    gate_args = TrainingArguments(
        output_dir=str(OUTPUT_DIR / "gating"),
        num_train_epochs=5,
        per_device_train_batch_size=128,
        per_device_eval_batch_size=128,
        learning_rate=3e-5,
        warmup_ratio=0.1,
        lr_scheduler_type="cosine",
        bf16=True,
        tf32=True,
        logging_steps=LOG_STEPS,
        eval_strategy="steps",
        eval_steps=100,
        save_strategy="steps",
        save_steps=100,
        save_total_limit=1,
        load_best_model_at_end=True,
        metric_for_best_model="accuracy",
        greater_is_better=True,
        report_to="wandb",
        dataloader_num_workers=2,
        optim="adamw_torch_fused",
        seed=SEED,
    )

    trainer = Trainer(
        model=model,
        args=gate_args,
        train_dataset=train_ds,
        eval_dataset=eval_ds,
        compute_metrics=compute_gate_metrics,
        data_collator=DataCollatorWithPadding(tokenizer),
        callbacks=[EarlyStoppingCallback(early_stopping_patience=3)],
    )
    trainer.train()

    print(f"[Gate] Pushing → {GATE_REPO}")
    trainer.model.push_to_hub(GATE_REPO, token=HF_TOKEN)
    tokenizer.push_to_hub(GATE_REPO, token=HF_TOKEN)

    wandb.finish()
    del model, trainer
    free_memory()
    print("[Gate] Done.")

# ────────────────────────────────────────────────────────────────────────────
# MAIN
# ────────────────────────────────────────────────────────────────────────────

def main():
    t0 = time.time()
    print("\n" + "█"*60)
    print("  AdaptRoute v4 — Training Pipeline Start (SFT + Gating Only)")
    print("█"*60 + "\n")

    # ── 1. Load data ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    N = 10000
    code_s    = load_code_data(n=N)
    math_s    = load_math_data(n=N)
    medical_s = load_medical_data(n=N)
    general_s = load_general_data(n=N)
    all_s     = code_s + math_s + medical_s + general_s
    random.shuffle(all_s)
    print(f"\n[Data] Total : {len(all_s)} samples across 4 classes\n")

    # ── 2-4. SFT domain adapters on base model ━━━━━━━━━━━━━━━━━━
    for domain, samples in [("medical", medical_s)]:
        run_sft_adapter(domain, samples, BASE_MODEL_ID)
        print(f"[Timer] After SFT-{domain:<8}: {(time.time()-t0)/3600:.2f} hrs")

    # ── 5. Gating network ━━━━━━━━━━━━━━━━━━━━━━━━━
    run_gate_training(all_s)
    print(f"[Timer] After gating      : {(time.time()-t0)/3600:.2f} hrs")

    # ── Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    total = (time.time()-t0)/3600
    print("\n" + "█"*60)
    print(f"  AdaptRoute v4 — Complete in {total:.2f} hrs")
    for d, r in ADAPTER_REPOS.items():
        print(f"  {d:<8} adapter → {r}")
    print(f"  Gate          → {GATE_REPO}")
    print("█"*60 + "\n")


if __name__ == "__main__":
    main()

"""### Evaluation: Inference with Gating and Adapters
This section provides a function to test the full pipeline: Gating -> Adapter Selection -> Generation.
"""

from peft import PeftModel

def fmt_inf(question: str) -> str:
    return (
        f"<start_of_turn>user\n{question.strip()}<end_of_turn>\n"
        f"<start_of_turn>model\n"   # no end_of_turn — let model generate
    )

# 2. Base Model Generation
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token

base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL_ID,
    torch_dtype=torch.bfloat16,
    device_map="auto"
)
gate_tokenizer = AutoTokenizer.from_pretrained(GATE_REPO)
gate_model = AutoModelForSequenceClassification.from_pretrained(GATE_REPO).to(DEVICE)

def run_inference_comparison(question: str):
    print(f"\nQuestion: {question}")
    print("-" * 40)

    # 1. Gating Prediction
    inputs = gate_tokenizer(question, return_tensors="pt", truncation=True, max_length=128).to(DEVICE)
    with torch.no_grad():
        logits = gate_model(**inputs).logits

    pred_id = torch.argmax(logits, dim=-1).item()
    domain = ID2LABEL[pred_id]
    print(f"[Gate] Predicted Domain: {domain.upper()}")

    prompt = fmt_inf(question)
    inputs = tokenizer(prompt, return_tensors="pt").to(DEVICE)

    # 3. Domain Adapter Generation (if applicable)
    if domain in ADAPTER_REPOS:
        print(f"\n[Adapter: {domain.upper()}] Loading and Generating...")
        # Load adapter onto base model
        model_with_adapter = PeftModel.from_pretrained(base_model, ADAPTER_REPOS[domain])

        adapter_out = model_with_adapter.generate(**inputs, max_new_tokens=512, do_sample=True, temperature=0.7)
        print(f"Adapted Response: \n{tokenizer.decode(adapter_out[0], skip_special_tokens=True).split('model\n')[-1]}")

        # Clean up to save VRAM
        del model_with_adapter
    else:
        base_out = base_model.generate(**inputs, max_new_tokens=512, do_sample=True, temperature=0.7)
        print(f"Base Response: {tokenizer.decode(base_out[0], skip_special_tokens=True).split('model\n')[-1]}")

    free_memory()

run_inference_comparison("How do I open a tight jar? just give me 1 way to do so.")

import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

def evaluate_gating_network(n_samples=50):
    print(f"Evaluating Gating Network with {n_samples} samples per class...")

    # 1. Prepare test data (using the load functions we defined)
    test_data = []
    test_data.extend(load_code_data(n=n_samples))
    test_data.extend(load_math_data(n=n_samples))
    test_data.extend(load_medical_data(n=n_samples))
    test_data.extend(load_general_data(n=n_samples))

    # 2. Load Gate Model and Tokenizer
    gate_tokenizer = AutoTokenizer.from_pretrained(GATE_REPO)
    gate_model = AutoModelForSequenceClassification.from_pretrained(GATE_REPO).to(DEVICE)
    gate_model.eval()

    y_true = []
    y_pred = []

    # 3. Run Inference
    for item in test_data:
        prompt = item['prompt']
        true_label = item['label']

        inputs = gate_tokenizer(prompt, return_tensors="pt", truncation=True, max_length=128).to(DEVICE)
        with torch.no_grad():
            logits = gate_model(**inputs).logits

        pred_id = torch.argmax(logits, dim=-1).item()
        pred_label = ID2LABEL[pred_id]

        y_true.append(true_label)
        y_pred.append(pred_label)

    # 4. Results
    print("\n--- Classification Report ---")
    print(classification_report(y_true, y_pred))

    # 5. Confusion Matrix Visualization
    cm = confusion_matrix(y_true, y_pred, labels=list(LABEL2ID.keys()))
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', xticklabels=LABEL2ID.keys(), yticklabels=LABEL2ID.keys(), cmap='Blues')
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.title('Gating Network Confusion Matrix')
    plt.show()

    del gate_model
    free_memory()

# Run the evaluation
evaluate_gating_network(n_samples=50)

